# Sirius Backend REST server:
backend:
  host: 'localhost'
  port: 2000
  rabc_exclude_code: 'exclude_code'

# Secret number - Used on simple crypt:
secret_number: 1618

# Pager settings (Lists):
pager:
  default_page_sizes: [10, 25, 50, 100]
  check_in_default_size: 1000

# Defaul Localization:
localization:
  default_country         : '858',
  default_country_isoCode : 'UY',
  default_country_name    : 'Uruguay',
  default_state_isoCode   : 'MO',
  default_state_name      : 'Montevideo',
  default_city_name       : 'Montevideo',
  default_doc_type        : '1',
  default_utc             : 'UTC-3'

# Default FullCalendar configuration:
# 0: resourceTimeGridDay , 1: resourceTimeGridWeek
fullcalendar:
  initialView: 1
  slotMinTime: '08:00:00',
  slotMaxTime: '18:00:00',
  slotDuration: '18:00:00',

# Patient password keywords:
pass_keywords: ["eucalipto", "pino", "roble", "cedro", "romero", "ficus", "cactus", "tacuara", "manzano", "higuera", "tero", "carpincho", "mulita", "yacare", "cardenal", "golondrina", "benteveo", "chaja", "jaguar", "dorado"]