version: "3"
services:
  sirius_database:
    container_name: sirius_database_container
    image: mongo:latest
    volumes:
      - ./database/data:/data/db
      - ./database/config:/data/configdb
    ports:
      - 27017:27017
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
    restart: unless-stopped
    networks:
      - sirius_net

  sirius_backend:
    container_name: sirius_backend_container
    image: node:latest
    volumes:
      - ./backend:/home/node/app
    ports:
      - 3000:3000
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      NODE_ENV: production
    user: node
    working_dir: /home/node/app
    command: "npm start"
    depends_on:
      - sirius_database
    restart: unless-stopped
    networks:
      - sirius_net

#  sirius_frontend:
#    container_name: sirius_frontend_container
#    image: nginx:alpine
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d/
#      - ./frontend/dist/sirius-ris:/usr/share/nginx/html:ro
#      # - ./nginx/ssl:/etc/ssl/
#    ports:
#     - 4000:4000
#    environment:
#      TZ: 'America/Argentina/Buenos_Aires'
#    restart: unless-stopped
#    networks:
#      - sirius_net

networks:
  sirius_net:
