version: "3.5"
services:
  opendicom_sirius_db:
    container_name: opendicom_sirius_db
    image: mongo:latest
    env_file: ./docker-compose.env
    volumes:
      - ./service_sirius_db/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./service_sirius_db/dumps:/dumps
      - ./service_sirius_db/data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - opendicom_net

  opendicom_sirius_backend:
    container_name: opendicom_sirius_backend
    image: opendicom/sirius-backend:1.0.0-beta.5
    env_file: ./docker-compose.env
    ports:
      - 2000:2000
    depends_on:
      - opendicom_sirius_db
    restart: unless-stopped
    networks:
      - opendicom_net

  opendicom_sirius_frontend:
    container_name: opendicom_sirius_frontend
    image: opendicom/sirius-frontend:1.0.0-beta.5
    env_file: ./docker-compose.env
    ports:
      - 4000:80
    depends_on:
      - opendicom_sirius_backend
    restart: unless-stopped
    networks:
      - opendicom_net

networks:
  opendicom_net:
    name: opendicom_net
